"""Immutable model package assembly.

Produces a self-contained directory artifact that includes all files
needed to deploy, audit, and reproduce a trained model:

    model.openvino/          # OpenVINO IR files (.xml + .bin)
    model.pytorch            # PyTorch checkpoint backup
    config.yaml              # Training hyperparameters snapshot
    conformal_quantiles.json # Calibration data
    calibration_set.txt      # Frame IDs used for calibration
    validation_report.json   # Three-step validation results
    training_job.json        # Full job metadata
    backbone_ref.txt         # Backbone version ID
    dataset_ref.txt          # Dataset version hash
    model_card.md            # Auto-generated human-readable summary
    SHA256SUMS               # Checksums of all files
    signature.sig            # HMAC-SHA256 signature (optional)
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import shutil
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import structlog

logger = structlog.get_logger()


def _sha256(path: Path) -> str:
    """Compute SHA256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _generate_model_card(
    camera_id: str | None,
    model_type: str | None,
    job_type: str,
    backbone_ref: str,
    dataset_ref: str,
    validation_report: dict | None,
    training_params: dict | None,
    created_at: str,
) -> str:
    """Generate a human-readable model card in Markdown format."""
    lines = [
        "# Model Card",
        "",
        f"- **Created**: {created_at}",
        f"- **Job Type**: {job_type}",
        f"- **Camera**: {camera_id or 'All (backbone)'}",
        f"- **Model Type**: {model_type or 'N/A'}",
        f"- **Backbone**: {backbone_ref}",
        f"- **Dataset**: {dataset_ref}",
        "",
    ]

    if training_params:
        lines.append("## Training Parameters")
        lines.append("")
        for k, v in training_params.items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")

    if validation_report:
        lines.append("## Validation Results")
        lines.append("")
        lines.append(f"- **All Passed**: {'Yes' if validation_report.get('all_passed') else 'No'}")
        if validation_report.get("auroc") is not None:
            lines.append(f"- **AUROC**: {validation_report['auroc']:.4f}")
        if validation_report.get("recall") is not None:
            lines.append(f"- **Synthetic Recall**: {validation_report['recall']:.4f}")
        if validation_report.get("replay"):
            rate = validation_report["replay"].get("new_detection_rate")
            if rate is not None:
                lines.append(f"- **Historical Replay Detection Rate**: {rate:.4f}")
        lines.append("")

        for step in validation_report.get("steps", []):
            status = "PASS" if step.get("passed") else ("SKIP" if step.get("skipped") else "FAIL")
            lines.append(f"### {step['name']} [{status}]")
            if step.get("metric_name"):
                lines.append(f"- {step['metric_name']}: {step.get('metric_value', 'N/A')}")
                lines.append(f"- Threshold: {step.get('threshold', 'N/A')}")
            if step.get("skip_reason"):
                lines.append(f"- Skip reason: {step['skip_reason']}")
            lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by Argus ModelPackager*")
    return "\n".join(lines)


class ModelPackager:
    """Assembles an immutable, self-contained model package."""

    def __init__(self, signing_key: str = ""):
        self._signing_key = signing_key

    def package(
        self,
        output_dir: Path,
        model_dir: Path,
        export_dir: Path | None,
        training_job: dict | None = None,
        validation_report: dict | None = None,
        calibration_path: Path | None = None,
        backbone_ref: str = "pretrained",
        dataset_ref: str = "",
        camera_id: str | None = None,
        model_type: str | None = None,
        training_params: dict | None = None,
        calibration_image_ids: list[str] | None = None,
    ) -> Path:
        """Assemble a complete model package.

        Args:
            output_dir: Where to create the package directory.
            model_dir: Training output directory (contains .ckpt files).
            export_dir: Export directory (contains .xml/.bin or .onnx files).
            training_job: Full TrainingJob dict for training_job.json.
            validation_report: ValidationReport dict for validation_report.json.
            calibration_path: Path to existing calibration.json.
            backbone_ref: Backbone version ID string.
            dataset_ref: Dataset version hash string.
            camera_id: Camera this model is for (None for backbone).
            model_type: Model type (patchcore, dinomaly2, etc.).
            training_params: Hyperparameters dict for config.yaml.
            calibration_image_ids: List of image paths used for calibration.

        Returns:
            Path to the created package directory.
        """
        # Pre-flight: verify output directory is writable
        output_dir.mkdir(parents=True, exist_ok=True)
        if not os.access(output_dir, os.W_OK):
            raise PermissionError(f"Output directory not writable: {output_dir}")

        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        short_id = uuid.uuid4().hex[:6]
        pkg_name = f"{camera_id or 'backbone'}_{model_type or 'ssl'}_{ts}_{short_id}"
        final_dir = output_dir / pkg_name

        # Assemble in a temp directory; atomic rename on success
        tmp_dir = output_dir / f".tmp_{pkg_name}"
        try:
            tmp_dir.mkdir(parents=True, exist_ok=True)
            self._assemble(
                pkg_dir=tmp_dir,
                model_dir=model_dir,
                export_dir=export_dir,
                training_job=training_job,
                validation_report=validation_report,
                calibration_path=calibration_path,
                backbone_ref=backbone_ref,
                dataset_ref=dataset_ref,
                camera_id=camera_id,
                model_type=model_type,
                training_params=training_params,
                calibration_image_ids=calibration_image_ids,
            )
            if final_dir.exists():
                shutil.rmtree(final_dir)
            tmp_dir.rename(final_dir)
        except Exception:
            # Clean up partial assembly
            if tmp_dir.exists():
                shutil.rmtree(tmp_dir, ignore_errors=True)
            raise

        return final_dir

    def _assemble(
        self,
        pkg_dir: Path,
        model_dir: Path,
        export_dir: Path | None,
        training_job: dict | None,
        validation_report: dict | None,
        calibration_path: Path | None,
        backbone_ref: str,
        dataset_ref: str,
        camera_id: str | None,
        model_type: str | None,
        training_params: dict | None,
        calibration_image_ids: list[str] | None,
    ) -> None:
        """Write all package files into *pkg_dir*."""
        created_at = datetime.now(timezone.utc).isoformat()

        # 1. Copy OpenVINO model files
        if export_dir and export_dir.exists():
            ov_dir = pkg_dir / "model.openvino"
            ov_dir.mkdir(exist_ok=True)
            for ext in ("*.xml", "*.bin", "*.onnx"):
                for f in export_dir.rglob(ext):
                    shutil.copy2(str(f), str(ov_dir / f.name))

        # 2. Copy PyTorch checkpoint
        for pattern in ("**/*.ckpt", "**/*.pt"):
            for ckpt in model_dir.glob(pattern):
                shutil.copy2(str(ckpt), str(pkg_dir / "model.pytorch"))
                break  # Only copy the first/best one

        # 3. config.yaml (training hyperparameters)
        if training_params:
            config_data = {
                "camera_id": camera_id,
                "model_type": model_type,
                "backbone_ref": backbone_ref,
                "dataset_ref": dataset_ref,
                "created_at": created_at,
                **training_params,
            }
            try:
                import yaml
                (pkg_dir / "config.yaml").write_text(
                    yaml.dump(config_data, default_flow_style=False, allow_unicode=True),
                    encoding="utf-8",
                )
            except ImportError:
                logger.warning(
                    "model_package.yaml_unavailable",
                    msg="PyYAML not installed, writing config.json instead",
                )
                (pkg_dir / "config.json").write_text(
                    json.dumps(config_data, indent=2, ensure_ascii=False),
                    encoding="utf-8",
                )

        # 4. conformal_quantiles.json
        if calibration_path and calibration_path.exists():
            shutil.copy2(str(calibration_path), str(pkg_dir / "conformal_quantiles.json"))

        # 5. calibration_set.txt
        if calibration_image_ids:
            (pkg_dir / "calibration_set.txt").write_text(
                "\n".join(calibration_image_ids), encoding="utf-8",
            )

        # 6. validation_report.json
        if validation_report:
            (pkg_dir / "validation_report.json").write_text(
                json.dumps(validation_report, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )

        # 7. training_job.json
        if training_job:
            (pkg_dir / "training_job.json").write_text(
                json.dumps(training_job, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )

        # 8. backbone_ref.txt
        (pkg_dir / "backbone_ref.txt").write_text(backbone_ref, encoding="utf-8")

        # 9. dataset_ref.txt
        (pkg_dir / "dataset_ref.txt").write_text(dataset_ref, encoding="utf-8")

        # 10. model_card.md
        card = _generate_model_card(
            camera_id=camera_id,
            model_type=model_type,
            job_type=training_job.get("job_type", "anomaly_head") if training_job else "unknown",
            backbone_ref=backbone_ref,
            dataset_ref=dataset_ref,
            validation_report=validation_report,
            training_params=training_params,
            created_at=created_at,
        )
        (pkg_dir / "model_card.md").write_text(card, encoding="utf-8")

        # 11. SHA256SUMS
        checksums = []
        for f in sorted(pkg_dir.rglob("*")):
            if f.is_file() and f.name not in ("SHA256SUMS", "signature.sig"):
                rel = f.relative_to(pkg_dir)
                checksums.append(f"{_sha256(f)}  {rel}")

        sums_content = "\n".join(checksums)
        (pkg_dir / "SHA256SUMS").write_text(sums_content, encoding="utf-8")

        # 12. signature.sig (HMAC-SHA256, optional)
        if self._signing_key:
            sig = hmac.new(
                self._signing_key.encode(), sums_content.encode(), hashlib.sha256,
            ).hexdigest()
            (pkg_dir / "signature.sig").write_text(sig, encoding="utf-8")

        logger.info(
            "model_package.created",
            path=str(pkg_dir),
            files=len(checksums),
            signed=bool(self._signing_key),
        )

    def verify(self, package_dir: Path) -> bool:
        """Verify package integrity using SHA256SUMS and optional signature."""
        sums_file = package_dir / "SHA256SUMS"
        if not sums_file.exists():
            logger.error("model_package.verify_failed", reason="SHA256SUMS missing")
            return False

        sums_content = sums_file.read_text(encoding="utf-8")

        # Verify signature if present
        sig_file = package_dir / "signature.sig"
        if sig_file.exists() and self._signing_key:
            expected_sig = sig_file.read_text(encoding="utf-8").strip()
            actual_sig = hmac.new(
                self._signing_key.encode(), sums_content.encode(), hashlib.sha256,
            ).hexdigest()
            if not hmac.compare_digest(expected_sig, actual_sig):
                logger.error("model_package.verify_failed", reason="Signature mismatch")
                return False

        # Verify each file hash
        for line in sums_content.strip().split("\n"):
            if not line.strip():
                continue
            # Support both "hash  path" (2 spaces) and "hash *path" (sha256sum binary mode)
            parts = line.split("  ", 1)
            if len(parts) != 2:
                parts = line.split(" *", 1)
            if len(parts) != 2:
                parts = line.split(" ", 1)
            if len(parts) != 2:
                continue
            expected_hash, rel_path = parts[0].strip(), parts[1].strip()
            file_path = package_dir / rel_path
            if not file_path.exists():
                logger.error("model_package.verify_failed", reason=f"Missing: {rel_path}")
                return False
            actual_hash = _sha256(file_path)
            if actual_hash != expected_hash:
                logger.error(
                    "model_package.verify_failed",
                    reason=f"Hash mismatch: {rel_path}",
                )
                return False

        logger.info("model_package.verified", path=str(package_dir))
        return True
